### ISSUE TITLE
Request: Add a warning to the repo

### ISSUE THREAD

**Issue by fuchsnj** [wyyerd/google-signin-rs#1]
Please add a very visible warning to the readme that this repo does not actually verify the JWT tokens yet.

It is currently very easy to a user to find this library on crates.io and assume it is handling auth correctly, without actually looking at the source code.
```
// TODO: Use JWT to verify the token with cache-control'd google certs
```

**Comment by kestred** [comment]
@fuchsnj --  that comment is actually quite a bit scarier than it sounds.

The crate *DOES* verify the token using a traditional OAuth flow,
which is slower than way Google recommends.

-------------------------------------------------------------

## For more context

Google provides two APIs for working with their Google Sign-In implementation:

1. An HTTPS endpoint to fetch the certificates for the token so that you may verify the JWT yourself.
2. An HTTPS endpoint to ask Google to verify the token for you per the usual OAuth flow.

This library currently uses implementation **Number 2** which makes an HTTP request to Google for every sign-in to verify the token.

Google's high-performance recommended solution is to make a single request to the first endpoint to get the certificate, parse the cache control headers, and refresh the certificate in a thread/etc periodically based on the cache expiry.  Then when logins are sent, the library can validate the tokens locally without having to make additional requests to Google.

**Comment by kestred** [comment]
For clarity, the method named `get_unsafe` is so named because it does not call the `verify` function which DOES do additional verification which Google strongly recommends, that the `get` function calls automatically for you (but I like to follow the principle of making APIs granular according to this philosophy: https://caseymuratori.com/blog_0016, so I still make the function available to API callers).

I will attempt to make all of these details clearer by adding more comments and improving function names.
